import { pool } from './pool.js';

const SUPPLIERS = [
  { name: 'Denso Auto Parts Phils', contact_person: 'Juan Dela Cruz', email: 'sales@denso.ph', phone: '09171234567' },
  { name: 'Sanden Climate Systems', contact_person: 'Maria Santos', email: 'contact@sanden.ph', phone: '09189876543' },
  { name: 'Valeo Automotive Phils', contact_person: 'Pedro Reyes', email: 'info@valeo.ph', phone: '09195551234' },
  { name: 'Bosch Auto Supplies', contact_person: 'Anna Gomez', email: 'support@bosch-auto.ph', phone: '09228889900' },
];

const DUMMY_PRODUCTS = [
  // 1. COMPRESSOR
  {
    sku: 'CMP-1023',
    name: 'Denso AC Compressor 10PA17C',
    brand: 'Denso',
    category: 'compressor',
    cost_price: 6200.00,
    selling_price: 7800.00,
    stock_quantity: 14,
    reorder_threshold: 4,
    unit: 'pc',
    compatible_vehicles: 'Toyota Vios 2013-2018',
    location_aisle: 'A1',
    location_shelf: 'S1',
    location_bin: 'B1',
    notes: 'OEM replacement compressor assembly for 1.3L & 1.5L engines.',
    supplier_index: 0,
  },
  {
    sku: 'CMP-1055',
    name: 'Sanden 5H14 Universal AC Compressor',
    brand: 'Sanden',
    category: 'compressor',
    cost_price: 5800.00,
    selling_price: 7200.00,
    stock_quantity: 8,
    reorder_threshold: 3,
    unit: 'pc',
    compatible_vehicles: 'Universal / Utility Trucks & Buses',
    location_aisle: 'A1',
    location_shelf: 'S1',
    location_bin: 'B2',
    notes: 'Heavy-duty 5-cylinder v-belt drive compressor.',
    supplier_index: 1,
  },
  {
    sku: 'CMP-1088',
    name: 'Valeo Rotary AC Compressor DKS15D',
    brand: 'Valeo',
    category: 'compressor',
    cost_price: 7100.00,
    selling_price: 8900.00,
    stock_quantity: 0, // OUT OF STOCK
    reorder_threshold: 4,
    unit: 'pc',
    compatible_vehicles: 'Nissan Navara D40 / Terra 2.5L',
    location_aisle: 'A1',
    location_shelf: 'S2',
    location_bin: 'B1',
    notes: 'Direct bolt-on replacement. Out of stock - supplier reorder required.',
    supplier_index: 2,
  },
  {
    sku: 'CMP-1102',
    name: 'Calsonic Kansei AC Compressor 10S17C',
    brand: 'Bosch',
    category: 'compressor',
    cost_price: 6800.00,
    selling_price: 8400.00,
    stock_quantity: 2, // LOW STOCK
    reorder_threshold: 5,
    unit: 'pc',
    compatible_vehicles: 'Mitsubishi Montero Sport 2016+',
    location_aisle: 'A1',
    location_shelf: 'S2',
    location_bin: 'B2',
    notes: 'Low stock warning. Includes clutch coil assembly.',
    supplier_index: 3,
  },

  // 2. CONDENSER
  {
    sku: 'CND-3010',
    name: 'Parallel Flow AC Condenser Assembly',
    brand: 'Denso',
    category: 'condenser',
    cost_price: 2900.00,
    selling_price: 3850.00,
    stock_quantity: 9,
    reorder_threshold: 3,
    unit: 'pc',
    compatible_vehicles: 'Toyota Innova 2016-2022',
    location_aisle: 'A2',
    location_shelf: 'S1',
    location_bin: 'B1',
    notes: 'High-efficiency parallel flow aluminum condenser.',
    supplier_index: 0,
  },
  {
    sku: 'CND-3045',
    name: 'Aluminum Fin & Tube Condenser Core',
    brand: 'Sanden',
    category: 'condenser',
    cost_price: 2400.00,
    selling_price: 3150.00,
    stock_quantity: 15,
    reorder_threshold: 4,
    unit: 'pc',
    compatible_vehicles: 'Honda Civic FC 2016-2021',
    location_aisle: 'A2',
    location_shelf: 'S1',
    location_bin: 'B2',
    notes: 'Lightweight high heat dissipation alloy.',
    supplier_index: 1,
  },
  {
    sku: 'CND-3090',
    name: 'Sub-Cool Condenser with Dryer Tank',
    brand: 'Valeo',
    category: 'condenser',
    cost_price: 3400.00,
    selling_price: 4400.00,
    stock_quantity: 1, // LOW STOCK
    reorder_threshold: 4,
    unit: 'pc',
    compatible_vehicles: 'Isuzu D-Max / MUX 2018+',
    location_aisle: 'A2',
    location_shelf: 'S2',
    location_bin: 'B1',
    notes: 'Integrated receiver drier bottle.',
    supplier_index: 2,
  },
  {
    sku: 'CND-3112',
    name: 'Heavy Duty Truck Dual Fan Condenser',
    brand: 'Bosch',
    category: 'condenser',
    cost_price: 5200.00,
    selling_price: 6900.00,
    stock_quantity: 0, // OUT OF STOCK
    reorder_threshold: 2,
    unit: 'pc',
    compatible_vehicles: 'Fuso Canter / Hino 300 Series',
    location_aisle: 'A2',
    location_shelf: 'S2',
    location_bin: 'B2',
    notes: 'Includes dual 12V 80W electric cooling fans.',
    supplier_index: 3,
  },

  // 3. EVAPORATOR
  {
    sku: 'EVP-2040',
    name: 'Sanden Laminated Evaporator Core',
    brand: 'Sanden',
    category: 'evaporator',
    cost_price: 1850.00,
    selling_price: 2450.00,
    stock_quantity: 3, // LOW STOCK
    reorder_threshold: 5,
    unit: 'pc',
    compatible_vehicles: 'Toyota Fortuner / Hilux 2016+',
    location_aisle: 'B1',
    location_shelf: 'S1',
    location_bin: 'B1',
    notes: 'Multi-layer anti-corrosion coating.',
    supplier_index: 1,
  },
  {
    sku: 'EVP-2075',
    name: 'Serpentine Aluminum Evaporator Core',
    brand: 'Denso',
    category: 'evaporator',
    cost_price: 1600.00,
    selling_price: 2100.00,
    stock_quantity: 12,
    reorder_threshold: 4,
    unit: 'pc',
    compatible_vehicles: 'Mitsubishi Mirage G4 / Hatchback',
    location_aisle: 'B1',
    location_shelf: 'S1',
    location_bin: 'B2',
    notes: 'Under-dash evaporator unit assembly.',
    supplier_index: 0,
  },
  {
    sku: 'EVP-2110',
    name: 'Multi-Tank Microchannel Evaporator',
    brand: 'Valeo',
    category: 'evaporator',
    cost_price: 2100.00,
    selling_price: 2800.00,
    stock_quantity: 0, // OUT OF STOCK
    reorder_threshold: 3,
    unit: 'pc',
    compatible_vehicles: 'Hyundai Starex / Grand Starex',
    location_aisle: 'B1',
    location_shelf: 'S2',
    location_bin: 'B1',
    notes: 'High-flow evaporator core.',
    supplier_index: 2,
  },
  {
    sku: 'EVP-2150',
    name: 'Rear Cabin Secondary Evaporator Core',
    brand: 'Denso',
    category: 'evaporator',
    cost_price: 1950.00,
    selling_price: 2600.00,
    stock_quantity: 6,
    reorder_threshold: 2,
    unit: 'pc',
    compatible_vehicles: 'Nissan Urvan NV350',
    location_aisle: 'B1',
    location_shelf: 'S2',
    location_bin: 'B2',
    notes: 'Rear ceiling A/C unit evaporator replacement.',
    supplier_index: 0,
  },

  // 4. EXPANSION_VALVE
  {
    sku: 'VAL-8820',
    name: 'Block Type Expansion Valve',
    brand: 'Denso',
    category: 'expansion_valve',
    cost_price: 450.00,
    selling_price: 680.00,
    stock_quantity: 2, // LOW STOCK
    reorder_threshold: 6,
    unit: 'pc',
    compatible_vehicles: 'Universal Toyota / Denso Fitment',
    location_aisle: 'B2',
    location_shelf: 'S1',
    location_bin: 'B1',
    notes: '1.5 Ton thermal expansion valve block.',
    supplier_index: 0,
  },
  {
    sku: 'VAL-8845',
    name: 'Angle Block Thermal Expansion Valve',
    brand: 'Sanden',
    category: 'expansion_valve',
    cost_price: 480.00,
    selling_price: 720.00,
    stock_quantity: 24,
    reorder_threshold: 5,
    unit: 'pc',
    compatible_vehicles: 'Honda City / Jazz GK 2014-2020',
    location_aisle: 'B2',
    location_shelf: 'S1',
    location_bin: 'B2',
    notes: 'Precision orifice metering valve.',
    supplier_index: 1,
  },
  {
    sku: 'VAL-8870',
    name: 'Flange Type TXV Expansion Valve',
    brand: 'Valeo',
    category: 'expansion_valve',
    cost_price: 520.00,
    selling_price: 790.00,
    stock_quantity: 0, // OUT OF STOCK
    reorder_threshold: 4,
    unit: 'pc',
    compatible_vehicles: 'Ford Ranger T6 / Everest 2.2L 3.2L',
    location_aisle: 'B2',
    location_shelf: 'S2',
    location_bin: 'B1',
    notes: 'Dual capillary tube TXV valve.',
    supplier_index: 2,
  },

  // 5. HOSE
  {
    sku: 'HOS-4015',
    name: 'High Pressure Discharge AC Hose Line',
    brand: 'Denso',
    category: 'hose',
    cost_price: 750.00,
    selling_price: 1150.00,
    stock_quantity: 11,
    reorder_threshold: 4,
    unit: 'pc',
    compatible_vehicles: 'Toyota Vios / Yaris 2013-2021',
    location_aisle: 'C1',
    location_shelf: 'S1',
    location_bin: 'B1',
    notes: 'Crimped aluminum fittings with R134a service port.',
    supplier_index: 0,
  },
  {
    sku: 'HOS-4040',
    name: 'Low Pressure Suction Hose Assembly',
    brand: 'Bosch',
    category: 'hose',
    cost_price: 820.00,
    selling_price: 1250.00,
    stock_quantity: 7,
    reorder_threshold: 3,
    unit: 'pc',
    compatible_vehicles: 'Mitsubishi L200 / Strada 2015+',
    location_aisle: 'C1',
    location_shelf: 'S1',
    location_bin: 'B2',
    notes: 'Reinforced 4-ply rubber barrier hose.',
    supplier_index: 3,
  },
  {
    sku: 'HOS-4085',
    name: 'Barrier AC Hose #8 (13/32" ID) 5-Meter Roll',
    brand: 'Sanden',
    category: 'hose',
    cost_price: 1450.00,
    selling_price: 2100.00,
    stock_quantity: 4,
    reorder_threshold: 2,
    unit: 'roll',
    compatible_vehicles: 'Universal Custom Hose Fabrications',
    location_aisle: 'C1',
    location_shelf: 'S2',
    location_bin: 'B1',
    notes: 'Bulk hose roll for shop custom line crimping.',
    supplier_index: 1,
  },

  // 6. SEAL_KIT
  {
    sku: 'SLK-6010',
    name: 'Universal Green HNBR O-Ring Kit 270pcs',
    brand: 'Bosch',
    category: 'seal_kit',
    cost_price: 350.00,
    selling_price: 550.00,
    stock_quantity: 35,
    reorder_threshold: 10,
    unit: 'set',
    compatible_vehicles: 'Universal Automotive AC Fittings',
    location_aisle: 'C2',
    location_shelf: 'S1',
    location_bin: 'B1',
    notes: 'R134a & R1234yf solvent-resistant green seals.',
    supplier_index: 3,
  },
  {
    sku: 'SLK-6035',
    name: 'Shaft Seal & Gasket Repair Kit for Denso 10PA',
    brand: 'Denso',
    category: 'seal_kit',
    cost_price: 420.00,
    selling_price: 680.00,
    stock_quantity: 4, // LOW STOCK
    reorder_threshold: 5,
    unit: 'set',
    compatible_vehicles: 'Denso 10PA15C / 10PA17C Compressors',
    location_aisle: 'C2',
    location_shelf: 'S1',
    location_bin: 'B2',
    notes: 'Includes carbon lip seal and body casing gaskets.',
    supplier_index: 0,
  },
  {
    sku: 'SLK-6105',
    name: 'Compressor Manifold Pad Seal Set',
    brand: 'Denso',
    category: 'seal_kit',
    cost_price: 180.00,
    selling_price: 320.00,
    stock_quantity: 0, // OUT OF STOCK
    reorder_threshold: 8,
    unit: 'set',
    compatible_vehicles: 'Toyota Dual AC Systems',
    location_aisle: 'C2',
    location_shelf: 'S2',
    location_bin: 'B2',
    notes: 'Sealing washers for manifold plate connections.',
    supplier_index: 0,
  },

  // 7. REFRIGERANT
  {
    sku: 'RFG-5001',
    name: 'R134a Refrigerant Canister 13.6kg',
    brand: 'Sanden',
    category: 'refrigerant',
    cost_price: 2400.00,
    selling_price: 3200.00,
    stock_quantity: 28,
    reorder_threshold: 8,
    unit: 'can',
    compatible_vehicles: 'Standard Automotive AC Systems',
    location_aisle: 'D1',
    location_shelf: 'S1',
    location_bin: 'B1',
    notes: '99.9% pure virgin R134a gas cylinder.',
    supplier_index: 1,
  },
  {
    sku: 'RFG-5025',
    name: 'R1234yf Eco Refrigerant 5kg Cylinder',
    brand: 'Bosch',
    category: 'refrigerant',
    cost_price: 8500.00,
    selling_price: 11500.00,
    stock_quantity: 3,
    reorder_threshold: 2,
    unit: 'can',
    compatible_vehicles: 'Modern Euro & US Import Vehicles (2020+)',
    location_aisle: 'D1',
    location_shelf: 'S1',
    location_bin: 'B2',
    notes: 'Low GWP next-gen refrigerant.',
    supplier_index: 3,
  },
  {
    sku: 'RFG-5090',
    name: 'PAG 46 Synthetic Compressor Oil 1L',
    brand: 'Denso',
    category: 'refrigerant',
    cost_price: 480.00,
    selling_price: 750.00,
    stock_quantity: 16,
    reorder_threshold: 5,
    unit: 'bottle',
    compatible_vehicles: 'R134a Rotary & Piston Compressors',
    location_aisle: 'D1',
    location_shelf: 'S2',
    location_bin: 'B2',
    notes: 'ISO VG46 viscosity synthetic lubricant.',
    supplier_index: 0,
  },

  // 8. DRYER_ACCUMULATOR
  {
    sku: 'DRY-7010',
    name: 'Aluminum Receiver Dryer Bottle with Sight Glass',
    brand: 'Denso',
    category: 'dryer_accumulator',
    cost_price: 320.00,
    selling_price: 520.00,
    stock_quantity: 19,
    reorder_threshold: 5,
    unit: 'pc',
    compatible_vehicles: 'Universal Inline AC Systems',
    location_aisle: 'D2',
    location_shelf: 'S1',
    location_bin: 'B1',
    notes: 'Integrated moisture indicator sight glass.',
    supplier_index: 0,
  },
  {
    sku: 'DRY-7040',
    name: 'Desiccant Bag Insert for Sub-Cool Condenser',
    brand: 'Sanden',
    category: 'dryer_accumulator',
    cost_price: 220.00,
    selling_price: 380.00,
    stock_quantity: 2, // LOW STOCK
    reorder_threshold: 6,
    unit: 'pc',
    compatible_vehicles: 'Toyota / Honda Sub-Cool Condensers',
    location_aisle: 'D2',
    location_shelf: 'S1',
    location_bin: 'B2',
    notes: 'Desiccant pouch with filter cap seal.',
    supplier_index: 1,
  },
  {
    sku: 'DRY-7115',
    name: 'Receiver Drier with Pressure Switch Port',
    brand: 'Valeo',
    category: 'dryer_accumulator',
    cost_price: 410.00,
    selling_price: 650.00,
    stock_quantity: 0, // OUT OF STOCK
    reorder_threshold: 4,
    unit: 'pc',
    compatible_vehicles: 'Mitsubishi Pajero / Montero Gen 2-3',
    location_aisle: 'D2',
    location_shelf: 'S2',
    location_bin: 'B2',
    notes: 'Dual pressure switch thread port.',
    supplier_index: 2,
  },

  // 9. BLOWER_MOTOR
  {
    sku: 'BLW-9015',
    name: 'AC Blower Motor Assembly with Fan Wheel',
    brand: 'Denso',
    category: 'blower_motor',
    cost_price: 1450.00,
    selling_price: 2150.00,
    stock_quantity: 13,
    reorder_threshold: 4,
    unit: 'pc',
    compatible_vehicles: 'Toyota Vios / Wigo / Avanza',
    location_aisle: 'E1',
    location_shelf: 'S1',
    location_bin: 'B1',
    notes: 'Balanced cage fan wheel motor.',
    supplier_index: 0,
  },
  {
    sku: 'BLW-9040',
    name: 'Front Main HVAC Blower Motor',
    brand: 'Bosch',
    category: 'blower_motor',
    cost_price: 1750.00,
    selling_price: 2500.00,
    stock_quantity: 6,
    reorder_threshold: 3,
    unit: 'pc',
    compatible_vehicles: 'Ford Everest / Ranger 2015+',
    location_aisle: 'E1',
    location_shelf: 'S1',
    location_bin: 'B2',
    notes: 'High RPM quiet operation blower.',
    supplier_index: 3,
  },
  {
    sku: 'BLW-9085',
    name: 'Rear Roof AC Auxiliary Blower Motor',
    brand: 'Valeo',
    category: 'blower_motor',
    cost_price: 1350.00,
    selling_price: 1950.00,
    stock_quantity: 1, // LOW STOCK
    reorder_threshold: 3,
    unit: 'pc',
    compatible_vehicles: 'Nissan NV350 / Urvan',
    location_aisle: 'E1',
    location_shelf: 'S2',
    location_bin: 'B1',
    notes: 'Ceiling evaporator blower motor.',
    supplier_index: 2,
  },

  // 10. OTHER
  {
    sku: 'OTH-9910',
    name: 'Digital AC Manifold Gauge Set with Hoses',
    brand: 'Bosch',
    category: 'other',
    cost_price: 3200.00,
    selling_price: 4500.00,
    stock_quantity: 4,
    reorder_threshold: 2,
    unit: 'set',
    compatible_vehicles: 'Technician Diagnostic Equipment',
    location_aisle: 'E2',
    location_shelf: 'S1',
    location_bin: 'B1',
    notes: 'Dual pressure gauge set with 60" hoses.',
    supplier_index: 3,
  },
  {
    sku: 'OTH-9935',
    name: 'Electronic Refrigerant Leak Detector',
    brand: 'Bosch',
    category: 'other',
    cost_price: 2800.00,
    selling_price: 3950.00,
    stock_quantity: 2,
    reorder_threshold: 1,
    unit: 'pc',
    compatible_vehicles: 'Shop Diagnostic Tooling',
    location_aisle: 'E2',
    location_shelf: 'S1',
    location_bin: 'B2',
    notes: 'Sniffer probe for R134a / R1234yf leaks.',
    supplier_index: 3,
  },
  {
    sku: 'OTH-9970',
    name: 'UV Leak Detection Dye & Flashlight Kit',
    brand: 'Sanden',
    category: 'other',
    cost_price: 650.00,
    selling_price: 980.00,
    stock_quantity: 15,
    reorder_threshold: 4,
    unit: 'set',
    compatible_vehicles: 'Universal AC Leak Tracing',
    location_aisle: 'E2',
    location_shelf: 'S2',
    location_bin: 'B1',
    notes: 'Includes fluorescent dye injector and UV lamp.',
    supplier_index: 1,
  },
];

async function seedDummyProducts() {
  console.log('Seeding dummy products for all categories...');

  // Ensure suppliers exist
  const supplierIds = [];
  for (const sup of SUPPLIERS) {
    const existing = await pool.query(`SELECT id FROM suppliers WHERE name = $1 LIMIT 1`, [sup.name]);
    if (existing.rows.length > 0) {
      supplierIds.push(existing.rows[0].id);
    } else {
      const res = await pool.query(
        `INSERT INTO suppliers (name, contact_person, email, phone)
         VALUES ($1, $2, $3, $4)
         RETURNING id;`,
        [sup.name, sup.contact_person, sup.email, sup.phone]
      );
      supplierIds.push(res.rows[0].id);
    }
  }

  let insertedCount = 0;
  for (const p of DUMMY_PRODUCTS) {
    const supplierId = supplierIds[p.supplier_index] || supplierIds[0];
    await pool.query(
      `INSERT INTO products 
       (sku, name, brand, category, unit, cost_price, selling_price, stock_quantity, reorder_threshold, supplier_id, compatible_vehicles, location_aisle, location_shelf, location_bin, notes, is_active)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, true)
       ON CONFLICT (sku) DO UPDATE SET
         name = EXCLUDED.name,
         category = EXCLUDED.category,
         brand = EXCLUDED.brand,
         stock_quantity = EXCLUDED.stock_quantity,
         reorder_threshold = EXCLUDED.reorder_threshold,
         cost_price = EXCLUDED.cost_price,
         selling_price = EXCLUDED.selling_price,
         location_aisle = EXCLUDED.location_aisle,
         location_shelf = EXCLUDED.location_shelf,
         location_bin = EXCLUDED.location_bin,
         is_active = true;`,
      [
        p.sku,
        p.name,
        p.brand,
        p.category,
        p.unit,
        p.cost_price,
        p.selling_price,
        p.stock_quantity,
        p.reorder_threshold,
        supplierId,
        p.compatible_vehicles,
        p.location_aisle,
        p.location_shelf,
        p.location_bin,
        p.notes,
      ]
    );
    insertedCount++;
  }

  console.log(`Successfully seeded ${insertedCount} dummy products across all 10 categories!`);
  await pool.end();
}

seedDummyProducts().catch((err) => {
  console.error('Error seeding dummy products:', err);
  process.exit(1);
});
